/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/example_interfaces/msg/ByteMultiArray.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/example_interfaces/msg/ByteMultiArray.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_BYTEMULTIARRAY_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_BYTEMULTIARRAY_H

#include "example_interfaces/msg/MultiArrayLayout.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_OCTET_DEFINED
#define DDS_SEQUENCE_OCTET_DEFINED
typedef struct dds_sequence_octet
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_octet;

#define dds_sequence_octet__alloc() \
((dds_sequence_octet*) dds_alloc (sizeof (dds_sequence_octet)));

#define dds_sequence_octet_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_OCTET_DEFINED */

typedef struct example_interfaces_msg_ByteMultiArray
{
  struct example_interfaces_msg_MultiArrayLayout layout;
  dds_sequence_octet data;
} example_interfaces_msg_ByteMultiArray;

extern const dds_topic_descriptor_t example_interfaces_msg_ByteMultiArray_desc;

#define example_interfaces_msg_ByteMultiArray__alloc() \
((example_interfaces_msg_ByteMultiArray*) dds_alloc (sizeof (example_interfaces_msg_ByteMultiArray)));

#define example_interfaces_msg_ByteMultiArray_free(d,o) \
dds_sample_free ((d), &example_interfaces_msg_ByteMultiArray_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_BYTEMULTIARRAY_H */
