/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/example_interfaces/msg/Float32MultiArray.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/example_interfaces/msg/Float32MultiArray.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_FLOAT32MULTIARRAY_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_FLOAT32MULTIARRAY_H

#include "example_interfaces/msg/MultiArrayLayout.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_FLOAT_DEFINED
#define DDS_SEQUENCE_FLOAT_DEFINED
typedef struct dds_sequence_float
{
  uint32_t _maximum;
  uint32_t _length;
  float *_buffer;
  bool _release;
} dds_sequence_float;

#define dds_sequence_float__alloc() \
((dds_sequence_float*) dds_alloc (sizeof (dds_sequence_float)));

#define dds_sequence_float_allocbuf(l) \
((float *) dds_alloc ((l) * sizeof (float)))
#endif /* DDS_SEQUENCE_FLOAT_DEFINED */

typedef struct example_interfaces_msg_Float32MultiArray
{
  struct example_interfaces_msg_MultiArrayLayout layout;
  dds_sequence_float data;
} example_interfaces_msg_Float32MultiArray;

extern const dds_topic_descriptor_t example_interfaces_msg_Float32MultiArray_desc;

#define example_interfaces_msg_Float32MultiArray__alloc() \
((example_interfaces_msg_Float32MultiArray*) dds_alloc (sizeof (example_interfaces_msg_Float32MultiArray)));

#define example_interfaces_msg_Float32MultiArray_free(d,o) \
dds_sample_free ((d), &example_interfaces_msg_Float32MultiArray_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_FLOAT32MULTIARRAY_H */
