/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/example_interfaces/msg/Int64MultiArray.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/example_interfaces/msg/Int64MultiArray.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_INT64MULTIARRAY_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_INT64MULTIARRAY_H

#include "example_interfaces/msg/MultiArrayLayout.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_INT64_DEFINED
#define DDS_SEQUENCE_INT64_DEFINED
typedef struct dds_sequence_int64
{
  uint32_t _maximum;
  uint32_t _length;
  int64_t *_buffer;
  bool _release;
} dds_sequence_int64;

#define dds_sequence_int64__alloc() \
((dds_sequence_int64*) dds_alloc (sizeof (dds_sequence_int64)));

#define dds_sequence_int64_allocbuf(l) \
((int64_t *) dds_alloc ((l) * sizeof (int64_t)))
#endif /* DDS_SEQUENCE_INT64_DEFINED */

typedef struct example_interfaces_msg_Int64MultiArray
{
  struct example_interfaces_msg_MultiArrayLayout layout;
  dds_sequence_int64 data;
} example_interfaces_msg_Int64MultiArray;

extern const dds_topic_descriptor_t example_interfaces_msg_Int64MultiArray_desc;

#define example_interfaces_msg_Int64MultiArray__alloc() \
((example_interfaces_msg_Int64MultiArray*) dds_alloc (sizeof (example_interfaces_msg_Int64MultiArray)));

#define example_interfaces_msg_Int64MultiArray_free(d,o) \
dds_sample_free ((d), &example_interfaces_msg_Int64MultiArray_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_INT64MULTIARRAY_H */
