/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/example_interfaces/msg/MultiArrayDimension.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/example_interfaces/msg/MultiArrayDimension.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_MULTIARRAYDIMENSION_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_MULTIARRAYDIMENSION_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct example_interfaces_msg_MultiArrayDimension
{
  char * label;
  uint32_t size;
  uint32_t stride;
} example_interfaces_msg_MultiArrayDimension;

extern const dds_topic_descriptor_t example_interfaces_msg_MultiArrayDimension_desc;

#define example_interfaces_msg_MultiArrayDimension__alloc() \
((example_interfaces_msg_MultiArrayDimension*) dds_alloc (sizeof (example_interfaces_msg_MultiArrayDimension)));

#define example_interfaces_msg_MultiArrayDimension_free(d,o) \
dds_sample_free ((d), &example_interfaces_msg_MultiArrayDimension_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_MULTIARRAYDIMENSION_H */
