/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/example_interfaces/msg/UInt16MultiArray.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/example_interfaces/msg/UInt16MultiArray.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_UINT16MULTIARRAY_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_UINT16MULTIARRAY_H

#include "example_interfaces/msg/MultiArrayLayout.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_UINT16_DEFINED
#define DDS_SEQUENCE_UINT16_DEFINED
typedef struct dds_sequence_uint16
{
  uint32_t _maximum;
  uint32_t _length;
  uint16_t *_buffer;
  bool _release;
} dds_sequence_uint16;

#define dds_sequence_uint16__alloc() \
((dds_sequence_uint16*) dds_alloc (sizeof (dds_sequence_uint16)));

#define dds_sequence_uint16_allocbuf(l) \
((uint16_t *) dds_alloc ((l) * sizeof (uint16_t)))
#endif /* DDS_SEQUENCE_UINT16_DEFINED */

typedef struct example_interfaces_msg_UInt16MultiArray
{
  struct example_interfaces_msg_MultiArrayLayout layout;
  dds_sequence_uint16 data;
} example_interfaces_msg_UInt16MultiArray;

extern const dds_topic_descriptor_t example_interfaces_msg_UInt16MultiArray_desc;

#define example_interfaces_msg_UInt16MultiArray__alloc() \
((example_interfaces_msg_UInt16MultiArray*) dds_alloc (sizeof (example_interfaces_msg_UInt16MultiArray)));

#define example_interfaces_msg_UInt16MultiArray_free(d,o) \
dds_sample_free ((d), &example_interfaces_msg_UInt16MultiArray_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_MSG_UINT16MULTIARRAY_H */
