/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: builtin_interfaces/msg/Time.h
  Source: builtin_interfaces/msg/Time.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_BUILTIN_INTERFACES_MSG_TIME_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_BUILTIN_INTERFACES_MSG_TIME_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct builtin_interfaces_msg_Time
{
  int32_t sec;
  uint32_t nanosec;
} builtin_interfaces_msg_Time;

extern const dds_topic_descriptor_t builtin_interfaces_msg_Time_desc;

#define builtin_interfaces_msg_Time__alloc() \
((builtin_interfaces_msg_Time*) dds_alloc (sizeof (builtin_interfaces_msg_Time)));

#define builtin_interfaces_msg_Time_free(d,o) \
dds_sample_free ((d), &builtin_interfaces_msg_Time_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_BUILTIN_INTERFACES_MSG_TIME_H */
