/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/rcl_interfaces/srv/DescribeParameters.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/rcl_interfaces/srv/DescribeParameters.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_SRV_DESCRIBEPARAMETERS_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_SRV_DESCRIBEPARAMETERS_H

#include "rcl_interfaces/msg/ParameterDescriptor.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_STRING_DEFINED
#define DDS_SEQUENCE_STRING_DEFINED
typedef struct dds_sequence_string
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} dds_sequence_string;

#define dds_sequence_string__alloc() \
((dds_sequence_string*) dds_alloc (sizeof (dds_sequence_string)));

#define dds_sequence_string_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
#endif /* DDS_SEQUENCE_STRING_DEFINED */

typedef struct rcl_interfaces_srv_DescribeParameters_Request
{
  dds_sequence_string names;
} rcl_interfaces_srv_DescribeParameters_Request;

extern const dds_topic_descriptor_t rcl_interfaces_srv_DescribeParameters_Request_desc;

#define rcl_interfaces_srv_DescribeParameters_Request__alloc() \
((rcl_interfaces_srv_DescribeParameters_Request*) dds_alloc (sizeof (rcl_interfaces_srv_DescribeParameters_Request)));

#define rcl_interfaces_srv_DescribeParameters_Request_free(d,o) \
dds_sample_free ((d), &rcl_interfaces_srv_DescribeParameters_Request_desc, (o))

#ifndef DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_DEFINED
#define DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_DEFINED
typedef struct dds_sequence_rcl_interfaces_msg_ParameterDescriptor
{
  uint32_t _maximum;
  uint32_t _length;
  struct rcl_interfaces_msg_ParameterDescriptor *_buffer;
  bool _release;
} dds_sequence_rcl_interfaces_msg_ParameterDescriptor;

#define dds_sequence_rcl_interfaces_msg_ParameterDescriptor__alloc() \
((dds_sequence_rcl_interfaces_msg_ParameterDescriptor*) dds_alloc (sizeof (dds_sequence_rcl_interfaces_msg_ParameterDescriptor)));

#define dds_sequence_rcl_interfaces_msg_ParameterDescriptor_allocbuf(l) \
((struct rcl_interfaces_msg_ParameterDescriptor *) dds_alloc ((l) * sizeof (struct rcl_interfaces_msg_ParameterDescriptor)))
#endif /* DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_DEFINED */

typedef struct rcl_interfaces_srv_DescribeParameters_Response
{
  dds_sequence_rcl_interfaces_msg_ParameterDescriptor descriptors;
} rcl_interfaces_srv_DescribeParameters_Response;

extern const dds_topic_descriptor_t rcl_interfaces_srv_DescribeParameters_Response_desc;

#define rcl_interfaces_srv_DescribeParameters_Response__alloc() \
((rcl_interfaces_srv_DescribeParameters_Response*) dds_alloc (sizeof (rcl_interfaces_srv_DescribeParameters_Response)));

#define rcl_interfaces_srv_DescribeParameters_Response_free(d,o) \
dds_sample_free ((d), &rcl_interfaces_srv_DescribeParameters_Response_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_SRV_DESCRIBEPARAMETERS_H */
