/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/rcl_interfaces/srv/GetParameterTypes.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/rcl_interfaces/srv/GetParameterTypes.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_SRV_GETPARAMETERTYPES_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_SRV_GETPARAMETERTYPES_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_STRING_DEFINED
#define DDS_SEQUENCE_STRING_DEFINED
typedef struct dds_sequence_string
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} dds_sequence_string;

#define dds_sequence_string__alloc() \
((dds_sequence_string*) dds_alloc (sizeof (dds_sequence_string)));

#define dds_sequence_string_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
#endif /* DDS_SEQUENCE_STRING_DEFINED */

typedef struct rcl_interfaces_srv_GetParameterTypes_Request
{
  dds_sequence_string names;
} rcl_interfaces_srv_GetParameterTypes_Request;

extern const dds_topic_descriptor_t rcl_interfaces_srv_GetParameterTypes_Request_desc;

#define rcl_interfaces_srv_GetParameterTypes_Request__alloc() \
((rcl_interfaces_srv_GetParameterTypes_Request*) dds_alloc (sizeof (rcl_interfaces_srv_GetParameterTypes_Request)));

#define rcl_interfaces_srv_GetParameterTypes_Request_free(d,o) \
dds_sample_free ((d), &rcl_interfaces_srv_GetParameterTypes_Request_desc, (o))

#ifndef DDS_SEQUENCE_UINT8_DEFINED
#define DDS_SEQUENCE_UINT8_DEFINED
typedef struct dds_sequence_uint8
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_uint8;

#define dds_sequence_uint8__alloc() \
((dds_sequence_uint8*) dds_alloc (sizeof (dds_sequence_uint8)));

#define dds_sequence_uint8_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_UINT8_DEFINED */

typedef struct rcl_interfaces_srv_GetParameterTypes_Response
{
  dds_sequence_uint8 types;
} rcl_interfaces_srv_GetParameterTypes_Response;

extern const dds_topic_descriptor_t rcl_interfaces_srv_GetParameterTypes_Response_desc;

#define rcl_interfaces_srv_GetParameterTypes_Response__alloc() \
((rcl_interfaces_srv_GetParameterTypes_Response*) dds_alloc (sizeof (rcl_interfaces_srv_GetParameterTypes_Response)));

#define rcl_interfaces_srv_GetParameterTypes_Response_free(d,o) \
dds_sample_free ((d), &rcl_interfaces_srv_GetParameterTypes_Response_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_SRV_GETPARAMETERTYPES_H */
