/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/rcl_interfaces/srv/SetLoggerLevels.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/rcl_interfaces/srv/SetLoggerLevels.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_SRV_SETLOGGERLEVELS_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_SRV_SETLOGGERLEVELS_H

#include "rcl_interfaces/msg/LoggerLevel.h"

#include "rcl_interfaces/msg/SetLoggerLevelsResult.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_RCL_INTERFACES_MSG_LOGGERLEVEL_DEFINED
#define DDS_SEQUENCE_RCL_INTERFACES_MSG_LOGGERLEVEL_DEFINED
typedef struct dds_sequence_rcl_interfaces_msg_LoggerLevel
{
  uint32_t _maximum;
  uint32_t _length;
  struct rcl_interfaces_msg_LoggerLevel *_buffer;
  bool _release;
} dds_sequence_rcl_interfaces_msg_LoggerLevel;

#define dds_sequence_rcl_interfaces_msg_LoggerLevel__alloc() \
((dds_sequence_rcl_interfaces_msg_LoggerLevel*) dds_alloc (sizeof (dds_sequence_rcl_interfaces_msg_LoggerLevel)));

#define dds_sequence_rcl_interfaces_msg_LoggerLevel_allocbuf(l) \
((struct rcl_interfaces_msg_LoggerLevel *) dds_alloc ((l) * sizeof (struct rcl_interfaces_msg_LoggerLevel)))
#endif /* DDS_SEQUENCE_RCL_INTERFACES_MSG_LOGGERLEVEL_DEFINED */

typedef struct rcl_interfaces_srv_SetLoggerLevels_Request
{
  dds_sequence_rcl_interfaces_msg_LoggerLevel levels;
} rcl_interfaces_srv_SetLoggerLevels_Request;

extern const dds_topic_descriptor_t rcl_interfaces_srv_SetLoggerLevels_Request_desc;

#define rcl_interfaces_srv_SetLoggerLevels_Request__alloc() \
((rcl_interfaces_srv_SetLoggerLevels_Request*) dds_alloc (sizeof (rcl_interfaces_srv_SetLoggerLevels_Request)));

#define rcl_interfaces_srv_SetLoggerLevels_Request_free(d,o) \
dds_sample_free ((d), &rcl_interfaces_srv_SetLoggerLevels_Request_desc, (o))

#ifndef DDS_SEQUENCE_RCL_INTERFACES_MSG_SETLOGGERLEVELSRESULT_DEFINED
#define DDS_SEQUENCE_RCL_INTERFACES_MSG_SETLOGGERLEVELSRESULT_DEFINED
typedef struct dds_sequence_rcl_interfaces_msg_SetLoggerLevelsResult
{
  uint32_t _maximum;
  uint32_t _length;
  struct rcl_interfaces_msg_SetLoggerLevelsResult *_buffer;
  bool _release;
} dds_sequence_rcl_interfaces_msg_SetLoggerLevelsResult;

#define dds_sequence_rcl_interfaces_msg_SetLoggerLevelsResult__alloc() \
((dds_sequence_rcl_interfaces_msg_SetLoggerLevelsResult*) dds_alloc (sizeof (dds_sequence_rcl_interfaces_msg_SetLoggerLevelsResult)));

#define dds_sequence_rcl_interfaces_msg_SetLoggerLevelsResult_allocbuf(l) \
((struct rcl_interfaces_msg_SetLoggerLevelsResult *) dds_alloc ((l) * sizeof (struct rcl_interfaces_msg_SetLoggerLevelsResult)))
#endif /* DDS_SEQUENCE_RCL_INTERFACES_MSG_SETLOGGERLEVELSRESULT_DEFINED */

typedef struct rcl_interfaces_srv_SetLoggerLevels_Response
{
  dds_sequence_rcl_interfaces_msg_SetLoggerLevelsResult results;
} rcl_interfaces_srv_SetLoggerLevels_Response;

extern const dds_topic_descriptor_t rcl_interfaces_srv_SetLoggerLevels_Response_desc;

#define rcl_interfaces_srv_SetLoggerLevels_Response__alloc() \
((rcl_interfaces_srv_SetLoggerLevels_Response*) dds_alloc (sizeof (rcl_interfaces_srv_SetLoggerLevels_Response)));

#define rcl_interfaces_srv_SetLoggerLevels_Response_free(d,o) \
dds_sample_free ((d), &rcl_interfaces_srv_SetLoggerLevels_Response_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_SRV_SETLOGGERLEVELS_H */
