/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: example_interfaces/srv/AddTwoInts.h
  Source: example_interfaces/srv/AddTwoInts.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_SRV_ADDTWOINTS_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_SRV_ADDTWOINTS_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct example_interfaces_srv_AddTwoInts_Request
{
  int64_t a;
  int64_t b;
} example_interfaces_srv_AddTwoInts_Request;

extern const dds_topic_descriptor_t example_interfaces_srv_AddTwoInts_Request_desc;

#define example_interfaces_srv_AddTwoInts_Request__alloc() \
((example_interfaces_srv_AddTwoInts_Request*) dds_alloc (sizeof (example_interfaces_srv_AddTwoInts_Request)));

#define example_interfaces_srv_AddTwoInts_Request_free(d,o) \
dds_sample_free ((d), &example_interfaces_srv_AddTwoInts_Request_desc, (o))

typedef struct example_interfaces_srv_AddTwoInts_Response
{
  int64_t sum;
} example_interfaces_srv_AddTwoInts_Response;

extern const dds_topic_descriptor_t example_interfaces_srv_AddTwoInts_Response_desc;

#define example_interfaces_srv_AddTwoInts_Response__alloc() \
((example_interfaces_srv_AddTwoInts_Response*) dds_alloc (sizeof (example_interfaces_srv_AddTwoInts_Response)));

#define example_interfaces_srv_AddTwoInts_Response_free(d,o) \
dds_sample_free ((d), &example_interfaces_srv_AddTwoInts_Response_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_EXAMPLE_INTERFACES_SRV_ADDTWOINTS_H */
