/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/rcl_interfaces/msg/FloatingPointRange.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/rcl_interfaces/msg/FloatingPointRange.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_FLOATINGPOINTRANGE_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_FLOATINGPOINTRANGE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct rcl_interfaces_msg_FloatingPointRange
{
  double from_value;
  double to_value;
  double step;
} rcl_interfaces_msg_FloatingPointRange;

extern const dds_topic_descriptor_t rcl_interfaces_msg_FloatingPointRange_desc;

#define rcl_interfaces_msg_FloatingPointRange__alloc() \
((rcl_interfaces_msg_FloatingPointRange*) dds_alloc (sizeof (rcl_interfaces_msg_FloatingPointRange)));

#define rcl_interfaces_msg_FloatingPointRange_free(d,o) \
dds_sample_free ((d), &rcl_interfaces_msg_FloatingPointRange_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_FLOATINGPOINTRANGE_H */
