/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/rcl_interfaces/msg/LoggerLevel.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/rcl_interfaces/msg/LoggerLevel.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_LOGGERLEVEL_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_LOGGERLEVEL_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define rcl_interfaces_msg_LoggerLevel_Constants_LOG_LEVEL_UNKNOWN 0
#define rcl_interfaces_msg_LoggerLevel_Constants_LOG_LEVEL_DEBUG 10
#define rcl_interfaces_msg_LoggerLevel_Constants_LOG_LEVEL_INFO 20
#define rcl_interfaces_msg_LoggerLevel_Constants_LOG_LEVEL_WARN 30
#define rcl_interfaces_msg_LoggerLevel_Constants_LOG_LEVEL_ERROR 40
#define rcl_interfaces_msg_LoggerLevel_Constants_LOG_LEVEL_FATAL 50
typedef struct rcl_interfaces_msg_LoggerLevel
{
  char * name;
  uint32_t level;
} rcl_interfaces_msg_LoggerLevel;

extern const dds_topic_descriptor_t rcl_interfaces_msg_LoggerLevel_desc;

#define rcl_interfaces_msg_LoggerLevel__alloc() \
((rcl_interfaces_msg_LoggerLevel*) dds_alloc (sizeof (rcl_interfaces_msg_LoggerLevel)));

#define rcl_interfaces_msg_LoggerLevel_free(d,o) \
dds_sample_free ((d), &rcl_interfaces_msg_LoggerLevel_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_LOGGERLEVEL_H */
