/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/rcl_interfaces/msg/ParameterDescriptor.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/rcl_interfaces/msg/ParameterDescriptor.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_H

#include "rcl_interfaces/msg/FloatingPointRange.h"

#include "rcl_interfaces/msg/IntegerRange.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_RCL_INTERFACES_MSG_FLOATINGPOINTRANGE_DEFINED
#define DDS_SEQUENCE_RCL_INTERFACES_MSG_FLOATINGPOINTRANGE_DEFINED
typedef struct dds_sequence_rcl_interfaces_msg_FloatingPointRange
{
  uint32_t _maximum;
  uint32_t _length;
  struct rcl_interfaces_msg_FloatingPointRange *_buffer;
  bool _release;
} dds_sequence_rcl_interfaces_msg_FloatingPointRange;

#define dds_sequence_rcl_interfaces_msg_FloatingPointRange__alloc() \
((dds_sequence_rcl_interfaces_msg_FloatingPointRange*) dds_alloc (sizeof (dds_sequence_rcl_interfaces_msg_FloatingPointRange)));

#define dds_sequence_rcl_interfaces_msg_FloatingPointRange_allocbuf(l) \
((struct rcl_interfaces_msg_FloatingPointRange *) dds_alloc ((l) * sizeof (struct rcl_interfaces_msg_FloatingPointRange)))
#endif /* DDS_SEQUENCE_RCL_INTERFACES_MSG_FLOATINGPOINTRANGE_DEFINED */

#ifndef DDS_SEQUENCE_RCL_INTERFACES_MSG_INTEGERRANGE_DEFINED
#define DDS_SEQUENCE_RCL_INTERFACES_MSG_INTEGERRANGE_DEFINED
typedef struct dds_sequence_rcl_interfaces_msg_IntegerRange
{
  uint32_t _maximum;
  uint32_t _length;
  struct rcl_interfaces_msg_IntegerRange *_buffer;
  bool _release;
} dds_sequence_rcl_interfaces_msg_IntegerRange;

#define dds_sequence_rcl_interfaces_msg_IntegerRange__alloc() \
((dds_sequence_rcl_interfaces_msg_IntegerRange*) dds_alloc (sizeof (dds_sequence_rcl_interfaces_msg_IntegerRange)));

#define dds_sequence_rcl_interfaces_msg_IntegerRange_allocbuf(l) \
((struct rcl_interfaces_msg_IntegerRange *) dds_alloc ((l) * sizeof (struct rcl_interfaces_msg_IntegerRange)))
#endif /* DDS_SEQUENCE_RCL_INTERFACES_MSG_INTEGERRANGE_DEFINED */

typedef struct rcl_interfaces_msg_ParameterDescriptor
{
  char * name;
  uint8_t type;
  char * description;
  char * additional_constraints;
  bool read_only;
  bool dynamic_typing;
  dds_sequence_rcl_interfaces_msg_FloatingPointRange floating_point_range;
  dds_sequence_rcl_interfaces_msg_IntegerRange integer_range;
} rcl_interfaces_msg_ParameterDescriptor;

extern const dds_topic_descriptor_t rcl_interfaces_msg_ParameterDescriptor_desc;

#define rcl_interfaces_msg_ParameterDescriptor__alloc() \
((rcl_interfaces_msg_ParameterDescriptor*) dds_alloc (sizeof (rcl_interfaces_msg_ParameterDescriptor)));

#define rcl_interfaces_msg_ParameterDescriptor_free(d,o) \
dds_sample_free ((d), &rcl_interfaces_msg_ParameterDescriptor_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_H */
