/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/rcl_interfaces/msg/ParameterType.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/rcl_interfaces/msg/ParameterType.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETERTYPE_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETERTYPE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define rcl_interfaces_msg_ParameterType_Constants_PARAMETER_NOT_SET 0
#define rcl_interfaces_msg_ParameterType_Constants_PARAMETER_BOOL 1
#define rcl_interfaces_msg_ParameterType_Constants_PARAMETER_INTEGER 2
#define rcl_interfaces_msg_ParameterType_Constants_PARAMETER_DOUBLE 3
#define rcl_interfaces_msg_ParameterType_Constants_PARAMETER_STRING 4
#define rcl_interfaces_msg_ParameterType_Constants_PARAMETER_BYTE_ARRAY 5
#define rcl_interfaces_msg_ParameterType_Constants_PARAMETER_BOOL_ARRAY 6
#define rcl_interfaces_msg_ParameterType_Constants_PARAMETER_INTEGER_ARRAY 7
#define rcl_interfaces_msg_ParameterType_Constants_PARAMETER_DOUBLE_ARRAY 8
#define rcl_interfaces_msg_ParameterType_Constants_PARAMETER_STRING_ARRAY 9
typedef struct rcl_interfaces_msg_ParameterType
{
  uint8_t structure_needs_at_least_one_member;
} rcl_interfaces_msg_ParameterType;

extern const dds_topic_descriptor_t rcl_interfaces_msg_ParameterType_desc;

#define rcl_interfaces_msg_ParameterType__alloc() \
((rcl_interfaces_msg_ParameterType*) dds_alloc (sizeof (rcl_interfaces_msg_ParameterType)));

#define rcl_interfaces_msg_ParameterType_free(d,o) \
dds_sample_free ((d), &rcl_interfaces_msg_ParameterType_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETERTYPE_H */
