/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/rcl_interfaces/msg/ParameterEventDescriptors.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/rcl_interfaces/msg/ParameterEventDescriptors.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETEREVENTDESCRIPTORS_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETEREVENTDESCRIPTORS_H

#include "rcl_interfaces/msg/ParameterDescriptor.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_DEFINED
#define DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_DEFINED
typedef struct dds_sequence_rcl_interfaces_msg_ParameterDescriptor
{
  uint32_t _maximum;
  uint32_t _length;
  struct rcl_interfaces_msg_ParameterDescriptor *_buffer;
  bool _release;
} dds_sequence_rcl_interfaces_msg_ParameterDescriptor;

#define dds_sequence_rcl_interfaces_msg_ParameterDescriptor__alloc() \
((dds_sequence_rcl_interfaces_msg_ParameterDescriptor*) dds_alloc (sizeof (dds_sequence_rcl_interfaces_msg_ParameterDescriptor)));

#define dds_sequence_rcl_interfaces_msg_ParameterDescriptor_allocbuf(l) \
((struct rcl_interfaces_msg_ParameterDescriptor *) dds_alloc ((l) * sizeof (struct rcl_interfaces_msg_ParameterDescriptor)))
#endif /* DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_DEFINED */

#ifndef DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_DEFINED
#define DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_DEFINED
typedef struct dds_sequence_rcl_interfaces_msg_ParameterDescriptor
{
  uint32_t _maximum;
  uint32_t _length;
  struct rcl_interfaces_msg_ParameterDescriptor *_buffer;
  bool _release;
} dds_sequence_rcl_interfaces_msg_ParameterDescriptor;

#define dds_sequence_rcl_interfaces_msg_ParameterDescriptor__alloc() \
((dds_sequence_rcl_interfaces_msg_ParameterDescriptor*) dds_alloc (sizeof (dds_sequence_rcl_interfaces_msg_ParameterDescriptor)));

#define dds_sequence_rcl_interfaces_msg_ParameterDescriptor_allocbuf(l) \
((struct rcl_interfaces_msg_ParameterDescriptor *) dds_alloc ((l) * sizeof (struct rcl_interfaces_msg_ParameterDescriptor)))
#endif /* DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_DEFINED */

#ifndef DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_DEFINED
#define DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_DEFINED
typedef struct dds_sequence_rcl_interfaces_msg_ParameterDescriptor
{
  uint32_t _maximum;
  uint32_t _length;
  struct rcl_interfaces_msg_ParameterDescriptor *_buffer;
  bool _release;
} dds_sequence_rcl_interfaces_msg_ParameterDescriptor;

#define dds_sequence_rcl_interfaces_msg_ParameterDescriptor__alloc() \
((dds_sequence_rcl_interfaces_msg_ParameterDescriptor*) dds_alloc (sizeof (dds_sequence_rcl_interfaces_msg_ParameterDescriptor)));

#define dds_sequence_rcl_interfaces_msg_ParameterDescriptor_allocbuf(l) \
((struct rcl_interfaces_msg_ParameterDescriptor *) dds_alloc ((l) * sizeof (struct rcl_interfaces_msg_ParameterDescriptor)))
#endif /* DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETERDESCRIPTOR_DEFINED */

typedef struct rcl_interfaces_msg_ParameterEventDescriptors
{
  dds_sequence_rcl_interfaces_msg_ParameterDescriptor new_parameters;
  dds_sequence_rcl_interfaces_msg_ParameterDescriptor changed_parameters;
  dds_sequence_rcl_interfaces_msg_ParameterDescriptor deleted_parameters;
} rcl_interfaces_msg_ParameterEventDescriptors;

extern const dds_topic_descriptor_t rcl_interfaces_msg_ParameterEventDescriptors_desc;

#define rcl_interfaces_msg_ParameterEventDescriptors__alloc() \
((rcl_interfaces_msg_ParameterEventDescriptors*) dds_alloc (sizeof (rcl_interfaces_msg_ParameterEventDescriptors)));

#define rcl_interfaces_msg_ParameterEventDescriptors_free(d,o) \
dds_sample_free ((d), &rcl_interfaces_msg_ParameterEventDescriptors_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETEREVENTDESCRIPTORS_H */
