/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/rcl_interfaces/msg/ParameterEvent.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/rcl_interfaces/msg/ParameterEvent.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETEREVENT_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETEREVENT_H

#include "builtin_interfaces/msg/Time.h"

#include "rcl_interfaces/msg/Parameter.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETER_DEFINED
#define DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETER_DEFINED
typedef struct dds_sequence_rcl_interfaces_msg_Parameter
{
  uint32_t _maximum;
  uint32_t _length;
  struct rcl_interfaces_msg_Parameter *_buffer;
  bool _release;
} dds_sequence_rcl_interfaces_msg_Parameter;

#define dds_sequence_rcl_interfaces_msg_Parameter__alloc() \
((dds_sequence_rcl_interfaces_msg_Parameter*) dds_alloc (sizeof (dds_sequence_rcl_interfaces_msg_Parameter)));

#define dds_sequence_rcl_interfaces_msg_Parameter_allocbuf(l) \
((struct rcl_interfaces_msg_Parameter *) dds_alloc ((l) * sizeof (struct rcl_interfaces_msg_Parameter)))
#endif /* DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETER_DEFINED */

#ifndef DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETER_DEFINED
#define DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETER_DEFINED
typedef struct dds_sequence_rcl_interfaces_msg_Parameter
{
  uint32_t _maximum;
  uint32_t _length;
  struct rcl_interfaces_msg_Parameter *_buffer;
  bool _release;
} dds_sequence_rcl_interfaces_msg_Parameter;

#define dds_sequence_rcl_interfaces_msg_Parameter__alloc() \
((dds_sequence_rcl_interfaces_msg_Parameter*) dds_alloc (sizeof (dds_sequence_rcl_interfaces_msg_Parameter)));

#define dds_sequence_rcl_interfaces_msg_Parameter_allocbuf(l) \
((struct rcl_interfaces_msg_Parameter *) dds_alloc ((l) * sizeof (struct rcl_interfaces_msg_Parameter)))
#endif /* DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETER_DEFINED */

#ifndef DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETER_DEFINED
#define DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETER_DEFINED
typedef struct dds_sequence_rcl_interfaces_msg_Parameter
{
  uint32_t _maximum;
  uint32_t _length;
  struct rcl_interfaces_msg_Parameter *_buffer;
  bool _release;
} dds_sequence_rcl_interfaces_msg_Parameter;

#define dds_sequence_rcl_interfaces_msg_Parameter__alloc() \
((dds_sequence_rcl_interfaces_msg_Parameter*) dds_alloc (sizeof (dds_sequence_rcl_interfaces_msg_Parameter)));

#define dds_sequence_rcl_interfaces_msg_Parameter_allocbuf(l) \
((struct rcl_interfaces_msg_Parameter *) dds_alloc ((l) * sizeof (struct rcl_interfaces_msg_Parameter)))
#endif /* DDS_SEQUENCE_RCL_INTERFACES_MSG_PARAMETER_DEFINED */

typedef struct rcl_interfaces_msg_ParameterEvent
{
  struct builtin_interfaces_msg_Time stamp;
  char * node;
  dds_sequence_rcl_interfaces_msg_Parameter new_parameters;
  dds_sequence_rcl_interfaces_msg_Parameter changed_parameters;
  dds_sequence_rcl_interfaces_msg_Parameter deleted_parameters;
} rcl_interfaces_msg_ParameterEvent;

extern const dds_topic_descriptor_t rcl_interfaces_msg_ParameterEvent_desc;

#define rcl_interfaces_msg_ParameterEvent__alloc() \
((rcl_interfaces_msg_ParameterEvent*) dds_alloc (sizeof (rcl_interfaces_msg_ParameterEvent)));

#define rcl_interfaces_msg_ParameterEvent_free(d,o) \
dds_sample_free ((d), &rcl_interfaces_msg_ParameterEvent_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETEREVENT_H */
