/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/rcl_interfaces/msg/ParameterValue.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/rcl_interfaces/msg/ParameterValue.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETERVALUE_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETERVALUE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_OCTET_DEFINED
#define DDS_SEQUENCE_OCTET_DEFINED
typedef struct dds_sequence_octet
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_octet;

#define dds_sequence_octet__alloc() \
((dds_sequence_octet*) dds_alloc (sizeof (dds_sequence_octet)));

#define dds_sequence_octet_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_OCTET_DEFINED */

#ifndef DDS_SEQUENCE_BOOL_DEFINED
#define DDS_SEQUENCE_BOOL_DEFINED
typedef struct dds_sequence_bool
{
  uint32_t _maximum;
  uint32_t _length;
  bool *_buffer;
  bool _release;
} dds_sequence_bool;

#define dds_sequence_bool__alloc() \
((dds_sequence_bool*) dds_alloc (sizeof (dds_sequence_bool)));

#define dds_sequence_bool_allocbuf(l) \
((bool *) dds_alloc ((l) * sizeof (bool)))
#endif /* DDS_SEQUENCE_BOOL_DEFINED */

#ifndef DDS_SEQUENCE_INT64_DEFINED
#define DDS_SEQUENCE_INT64_DEFINED
typedef struct dds_sequence_int64
{
  uint32_t _maximum;
  uint32_t _length;
  int64_t *_buffer;
  bool _release;
} dds_sequence_int64;

#define dds_sequence_int64__alloc() \
((dds_sequence_int64*) dds_alloc (sizeof (dds_sequence_int64)));

#define dds_sequence_int64_allocbuf(l) \
((int64_t *) dds_alloc ((l) * sizeof (int64_t)))
#endif /* DDS_SEQUENCE_INT64_DEFINED */

#ifndef DDS_SEQUENCE_DOUBLE_DEFINED
#define DDS_SEQUENCE_DOUBLE_DEFINED
typedef struct dds_sequence_double
{
  uint32_t _maximum;
  uint32_t _length;
  double *_buffer;
  bool _release;
} dds_sequence_double;

#define dds_sequence_double__alloc() \
((dds_sequence_double*) dds_alloc (sizeof (dds_sequence_double)));

#define dds_sequence_double_allocbuf(l) \
((double *) dds_alloc ((l) * sizeof (double)))
#endif /* DDS_SEQUENCE_DOUBLE_DEFINED */

#ifndef DDS_SEQUENCE_STRING_DEFINED
#define DDS_SEQUENCE_STRING_DEFINED
typedef struct dds_sequence_string
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} dds_sequence_string;

#define dds_sequence_string__alloc() \
((dds_sequence_string*) dds_alloc (sizeof (dds_sequence_string)));

#define dds_sequence_string_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
#endif /* DDS_SEQUENCE_STRING_DEFINED */

typedef struct rcl_interfaces_msg_ParameterValue
{
  uint8_t type;
  bool bool_value;
  int64_t integer_value;
  double double_value;
  char * string_value;
  dds_sequence_octet byte_array_value;
  dds_sequence_bool bool_array_value;
  dds_sequence_int64 integer_array_value;
  dds_sequence_double double_array_value;
  dds_sequence_string string_array_value;
} rcl_interfaces_msg_ParameterValue;

extern const dds_topic_descriptor_t rcl_interfaces_msg_ParameterValue_desc;

#define rcl_interfaces_msg_ParameterValue__alloc() \
((rcl_interfaces_msg_ParameterValue*) dds_alloc (sizeof (rcl_interfaces_msg_ParameterValue)));

#define rcl_interfaces_msg_ParameterValue_free(d,o) \
dds_sample_free ((d), &rcl_interfaces_msg_ParameterValue_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_PARAMETERVALUE_H */
