/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/r22052/workspace/csdk/build/autel_msgs/src/rcl_interfaces/msg/SetParametersResult.h
  Source: /home/r22052/workspace/csdk/build/autel_msgs/idl/rcl_interfaces/msg/SetParametersResult.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_SETPARAMETERSRESULT_H
#define DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_SETPARAMETERSRESULT_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct rcl_interfaces_msg_SetParametersResult
{
  bool successful;
  char * reason;
} rcl_interfaces_msg_SetParametersResult;

extern const dds_topic_descriptor_t rcl_interfaces_msg_SetParametersResult_desc;

#define rcl_interfaces_msg_SetParametersResult__alloc() \
((rcl_interfaces_msg_SetParametersResult*) dds_alloc (sizeof (rcl_interfaces_msg_SetParametersResult)));

#define rcl_interfaces_msg_SetParametersResult_free(d,o) \
dds_sample_free ((d), &rcl_interfaces_msg_SetParametersResult_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_R22052_WORKSPACE_CSDK_BUILD_AUTEL_MSGS_SRC_RCL_INTERFACES_MSG_SETPARAMETERSRESULT_H */
